import '../../models/westops/traffic_code.dart';

// TODO: Add `HttpTrafficCodesRepository` once the backend ships
// `/api/v1/westops/traffic-codes`. It should reuse the existing
// `HttpDocumentHubApiClient` in `lib/services/api/` rather than rolling its
// own transport.
abstract class TrafficCodesRepository {
  Future<List<TrafficCode>> listAll();
}

/// Full Road Traffic Act offence schedule (147 entries), ported from the
/// WestOps app's `lib/modles/trafficCode.dart`.
class InMemoryTrafficCodesRepository implements TrafficCodesRepository {
  const InMemoryTrafficCodesRepository();

  @override
  Future<List<TrafficCode>> listAll() async => _seedRecords;

  static const List<TrafficCode> _seedRecords = [
    TrafficCode(
      code: 'D001',
      offenceDescription: 'Aid And Abet No Driver’s Licence or Permit',
      fineAmount: 15000.0,
      demeritPoints: 0,
      legalSection: 'Section 20(4)',
    ),
    TrafficCode(
      code: 'D002',
      offenceDescription: 'Aid And Abet Operating Motor Vehicle Contrary To The Terms Of Insurance Coverage While Acting As A Driving Instructor',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 180(2)',
    ),
    TrafficCode(
      code: 'D003',
      offenceDescription: 'Body Protruding',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 261(4)',
    ),
    TrafficCode(
      code: 'D004',
      offenceDescription: 'Breach of special permit',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 113(8)',
    ),
    TrafficCode(
      code: 'D005',
      offenceDescription: 'Careless Driving Causing Collision',
      fineAmount: 25000.0,
      demeritPoints: 10,
      legalSection: 'Section 59(1)',
    ),
    TrafficCode(
      code: 'D006',
      offenceDescription: 'Careless Driving Where No Collision Occurs',
      fineAmount: 11000.0,
      demeritPoints: 4,
      legalSection: 'Section 59(1)',
    ),
    TrafficCode(
      code: 'D007',
      offenceDescription: 'Carrying dangerous goods without the transport emergency cards and manifest  Or Not Producing Emergency Cards And Manifests Upon Being Requested  By A Constable Or Other Authorized Person',
      fineAmount: 175000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 291(3)',
    ),
    TrafficCode(
      code: 'D008',
      offenceDescription: 'Carrying passenger on motor cycle on any part other than the sidecar',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 261(4)',
    ),
    TrafficCode(
      code: 'D009',
      offenceDescription: 'Carrying Person Otherwise Than By Sitting Astride On Motor Cycle',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 67(2)',
    ),
    TrafficCode(
      code: 'D010',
      offenceDescription: 'Causing Motor Cycle To Be Driven On One Wheel Only',
      fineAmount: 5000.0,
      demeritPoints: 3,
      legalSection: 'Section 67(2)',
    ),
    TrafficCode(
      code: 'D011',
      offenceDescription: 'Child Without Child Restraint System In Motor Vehicle',
      fineAmount: 5000.0,
      demeritPoints: 4,
      legalSection: 'Section 73(2)',
    ),
    TrafficCode(
      code: 'D012',
      offenceDescription: 'Crossing From A Minor Road To Major Road So As To Obstruct Traffic',
      fineAmount: 8000.0,
      demeritPoints: 3,
      legalSection: 'Section 54(4)b',
    ),
    TrafficCode(
      code: 'D013',
      offenceDescription: 'Crossing Road So As To Obstruct Traffic',
      fineAmount: 9000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(5)(d)(iii)',
    ),
    TrafficCode(
      code: 'D014',
      offenceDescription: 'Direction indicator contrary to Regulations',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 110(3)',
    ),
    TrafficCode(
      code: 'D015',
      offenceDescription: 'Disobeying Traffic Light Or Stop Sign',
      fineAmount: 10000.0,
      demeritPoints: 6,
      legalSection: 'Section 52(2)(a)',
    ),
    TrafficCode(
      code: 'D016',
      offenceDescription: 'Drawing More Than Prescribed Number of Trailers',
      fineAmount: 12000.0,
      demeritPoints: 4,
      legalSection: 'Section 68(3)',
    ),
    TrafficCode(
      code: 'D017',
      offenceDescription: 'Driver Accompanying Learner Driver Having Excess Alcohol',
      fineAmount: 12000.0,
      demeritPoints: 0,
      legalSection: 'Section 24(4)',
    ),
    TrafficCode(
      code: 'D018',
      offenceDescription: 'Driver Failing to Cause Passenger To Wear Seatbelt',
      fineAmount: 2000.0,
      demeritPoints: 2,
      legalSection: 'Section 72(4)',
    ),
    TrafficCode(
      code: 'D019',
      offenceDescription: 'Driver Not Ensuring Pillion Wears Helmet',
      fineAmount: 8000.0,
      demeritPoints: 2,
      legalSection: 'Section 74(3)',
    ),
    TrafficCode(
      code: 'D020',
      offenceDescription: 'Driver Overtaking Without A Clear View',
      fineAmount: 10000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(5)(d)(i)',
    ),
    TrafficCode(
      code: 'D021',
      offenceDescription: 'Driving a non-emergency  vehicle over a Jamaica Fire Brigade hose laid on the road for the use at a fire without consent of a Constable or other person controlling traffic or Superintendent or other officer of the JFB',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 284(2)',
    ),
    TrafficCode(
      code: 'D022',
      offenceDescription: 'Driving Backwards Unnecessarily',
      fineAmount: 3000.0,
      demeritPoints: 4,
      legalSection: 'Section 57(5)(f)',
    ),
    TrafficCode(
      code: 'D023',
      offenceDescription: 'Driving closer than 50 meters behind an emergency vehicle or driving or stopping within 100 meters of where an emergency vehicle stopped',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 283(2)',
    ),
    TrafficCode(
      code: 'D024',
      offenceDescription: 'Driving Defective Motor Vehicle',
      fineAmount: 10000.0,
      demeritPoints: 2,
      legalSection: 'Section 123(d)',
    ),
    TrafficCode(
      code: 'D025',
      offenceDescription: 'Driving From A Place That Is Not A Road Onto A Road So As To Obstruct Traffic',
      fineAmount: 9000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(5) (e)',
    ),
    TrafficCode(
      code: 'D026',
      offenceDescription: 'Driving Instructor Holding Or Using Electronic Communication Device While Providing Instructions',
      fineAmount: 10000.0,
      demeritPoints: 6,
      legalSection: 'Section 121(4)',
    ),
    TrafficCode(
      code: 'D027',
      offenceDescription: 'Driving Or Attempting To Drive Motor Vehicle Across Funeral Procession',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 123(h)',
    ),
    TrafficCode(
      code: 'D028',
      offenceDescription: 'Driving/Operating Motor Vehicle While Using Electronic Communication Device',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 121(4)',
    ),
    TrafficCode(
      code: 'D029',
      offenceDescription: 'Driving/Operating Motor Vehicle While Using Specified Electronic Visual Device Within Driver’s Line Of Sight',
      fineAmount: 10000.0,
      demeritPoints: 6,
      legalSection: 'Section 122(3)',
    ),
    TrafficCode(
      code: 'D030',
      offenceDescription: 'Driving/Riding in a Motor Vehicle Without Seatbelt On',
      fineAmount: 2000.0,
      demeritPoints: 2,
      legalSection: 'Section 72(4)',
    ),
    TrafficCode(
      code: 'D031',
      offenceDescription: 'Exceeding Speed Limit In Construction Zone; 33-49 Kilometers Per Hour',
      fineAmount: 20000.0,
      demeritPoints: 6,
      legalSection: 'Section (77)(3)',
    ),
    TrafficCode(
      code: 'D032',
      offenceDescription: 'Exceeding Speed Limit In Construction Zone;16-32 Kilometers Per Hour',
      fineAmount: 12000.0,
      demeritPoints: 3,
      legalSection: 'Section 77(3)',
    ),
    TrafficCode(
      code: 'D033',
      offenceDescription: 'Exceeding Speed Limit In Construction Zone;50 Or More Kilometers Per Hour',
      fineAmount: 30000.0,
      demeritPoints: 10,
      legalSection: 'Section 77(3)',
    ),
    TrafficCode(
      code: 'D034',
      offenceDescription: 'Exceeding Speed Limit In School Safety Zone; 16 To 32 Kilometers Per Hour',
      fineAmount: 12000.0,
      demeritPoints: 3,
      legalSection: 'Section 76(4)',
    ),
    TrafficCode(
      code: 'D035',
      offenceDescription: 'Exceeding Speed Limit In School Safety Zone; 33 To 49 Kilometers Per Hour',
      fineAmount: 20000.0,
      demeritPoints: 6,
      legalSection: 'Section 76(4)',
    ),
    TrafficCode(
      code: 'D036',
      offenceDescription: 'Exceeding Speed Limit In School Safety Zone; 50 or More Kilometres Per Hour',
      fineAmount: 30000.0,
      demeritPoints: 10,
      legalSection: 'Section 76(4)',
    ),
    TrafficCode(
      code: 'D037',
      offenceDescription: 'Exceeding Speed Limit; 16-32 Kilometers Per Hour',
      fineAmount: 6000.0,
      demeritPoints: 2,
      legalSection: 'Section 55(3)',
    ),
    TrafficCode(
      code: 'D038',
      offenceDescription: 'Exceeding Speed Limit; 33-49 Kilometers Per Hour',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 55(3)',
    ),
    TrafficCode(
      code: 'D039',
      offenceDescription: 'Exceeding Speed Limit; 50 Or More Kilometers Per Hour',
      fineAmount: 15000.0,
      demeritPoints: 6,
      legalSection: 'Section 55(3)',
    ),
    TrafficCode(
      code: 'D040',
      offenceDescription: 'Excess Noise',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 247(7)',
    ),
    TrafficCode(
      code: 'D041',
      offenceDescription: 'Excess Weight 1001-5000 Kilogram',
      fineAmount: 100000.0,
      demeritPoints: 0,
      legalSection: 'Section 102(1)(b)',
    ),
    TrafficCode(
      code: 'D042',
      offenceDescription: 'Excess Weight 500-1000 Kilogram',
      fineAmount: 25000.0,
      demeritPoints: 0,
      legalSection: 'Section 102(1)(a)',
    ),
    TrafficCode(
      code: 'D043',
      offenceDescription: 'Failing To Allow Vehicle To Be Overtaken',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 57(5)(c)',
    ),
    TrafficCode(
      code: 'D044',
      offenceDescription: 'Failing To Bring Motor Vehicle To A Full Stop Where No Traffic Sign is Posted Or Constable is Assigned',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 54(4)(a)(ii)',
    ),
    TrafficCode(
      code: 'D045',
      offenceDescription: 'Failing To Comply With Other Traffic  Signs',
      fineAmount: 6000.0,
      demeritPoints: 3,
      legalSection: 'Section 52(2)(b)',
    ),
    TrafficCode(
      code: 'D046',
      offenceDescription: 'Failing To Comply With Requirement To Off-Load Vehicle When Vehicle Is Found To Be Above Prescribed Laden Weight In A Manner So As Not To Obstruct Traffic',
      fineAmount: 7000.0,
      demeritPoints: 0,
      legalSection: 'Section 104(3)',
    ),
    TrafficCode(
      code: 'D047',
      offenceDescription: 'Failing To Comply With Terms And Conditions Of Driver’s Licence',
      fineAmount: 6000.0,
      demeritPoints: 2,
      legalSection: 'Section 27(3)',
    ),
    TrafficCode(
      code: 'D048',
      offenceDescription: 'Failing To Comply With Terms And Conditions Of Learner’s Permit',
      fineAmount: 6000.0,
      demeritPoints: 2,
      legalSection: 'Section 24(4)',
    ),
    TrafficCode(
      code: 'D049',
      offenceDescription: 'Failing To Comply With Terms Of Condition Of Driver’s Licence During First Twelve (12) Months',
      fineAmount: 6000.0,
      demeritPoints: 2,
      legalSection: 'Section 27(3)',
    ),
    TrafficCode(
      code: 'D050',
      offenceDescription: 'Failing To Comply With Traffic Sign In Construction Zone',
      fineAmount: 10000.0,
      demeritPoints: 3,
      legalSection: 'Section 77(3)',
    ),
    TrafficCode(
      code: 'D051',
      offenceDescription: 'Failing To Comply With Traffic Sign In School Zone',
      fineAmount: 10000.0,
      demeritPoints: 2,
      legalSection: 'Section 76(4)',
    ),
    TrafficCode(
      code: 'D052',
      offenceDescription: 'Failing To Comply With Traffic Signs Or Direction Of Constable Before Turning Into or Crossing a Major Road Where Roadway Is Not Controlled By Traffic Light',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 54(4)(a)(i)',
    ),
    TrafficCode(
      code: 'D053',
      offenceDescription: 'Failing To Fit Mechanical or illuminated Device (No indicator)',
      fineAmount: 2500.0,
      demeritPoints: 2,
      legalSection: 'Section 90(6)',
    ),
    TrafficCode(
      code: 'D054',
      offenceDescription: 'Failing To Give Appropriate Signal When Approaching A Constable At Road Junction To Indicate Which Direction Driver Will Go',
      fineAmount: 2500.0,
      demeritPoints: 2,
      legalSection: 'Section 90(6)',
    ),
    TrafficCode(
      code: 'D055',
      offenceDescription: 'Failing To Give Signal To Stop',
      fineAmount: 2500.0,
      demeritPoints: 2,
      legalSection: 'Section 90(6)',
    ),
    TrafficCode(
      code: 'D056',
      offenceDescription: 'Failing To Give Turning Signal (Failing to Indicate)',
      fineAmount: 2500.0,
      demeritPoints: 2,
      legalSection: 'Section 90(6)',
    ),
    TrafficCode(
      code: 'D057',
      offenceDescription: 'Failing to have certificate showing exemption from wearing seatbelt',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 281(3)',
    ),
    TrafficCode(
      code: 'D058',
      offenceDescription: 'Failing to inform police of route where radioactive or infectious goods will be transported at least five days before transportation',
      fineAmount: 25000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 294(2)',
    ),
    TrafficCode(
      code: 'D059',
      offenceDescription: 'Failing To Keep Left Or Nearside Of The Road When Being Overtaken',
      fineAmount: 5000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(5)(a)',
    ),
    TrafficCode(
      code: 'D060',
      offenceDescription: 'Failing To Keep Right Or Offside Of Other Traffic Whilst Overtaking',
      fineAmount: 5000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(5)(b)',
    ),
    TrafficCode(
      code: 'D061',
      offenceDescription: 'Failing to label protective device',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 276(4)',
    ),
    TrafficCode(
      code: 'D062',
      offenceDescription: 'Failing To Obey Constable Command',
      fineAmount: 5000.0,
      demeritPoints: 1,
      legalSection: 'Section 91(2)',
    ),
    TrafficCode(
      code: 'D063',
      offenceDescription: 'Failing To Observe Silent Zone',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 75(1)',
    ),
    TrafficCode(
      code: 'D064',
      offenceDescription: 'Failing To Observe Stop For Crossing When Required By A School Crossing Warden',
      fineAmount: 12000.0,
      demeritPoints: 6,
      legalSection: 'Section 81(3)(a)',
    ),
    TrafficCode(
      code: 'D065',
      offenceDescription: 'Failing To Place Motor Vehicle Not In Motion As Indicated By Constable Or By Notice Issued By The Authority',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D066',
      offenceDescription: 'Failing To Place Motor Vehicle When Not In Motion In A Safe Position',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D067',
      offenceDescription: 'Failing To Produce Driver’s Licence/Permit At Constable’s Request',
      fineAmount: 2000.0,
      demeritPoints: 0,
      legalSection: 'Section 20(4)',
    ),
    TrafficCode(
      code: 'D068',
      offenceDescription: 'Failing to prominently display license or certified copy at driving school',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 188(2)',
    ),
    TrafficCode(
      code: 'D069',
      offenceDescription: 'Failing To Remain Stationery When Stopped By School Crossing Warden',
      fineAmount: 12000.0,
      demeritPoints: 6,
      legalSection: 'Section 81(3)(b)',
    ),
    TrafficCode(
      code: 'D070',
      offenceDescription: 'Failing To Stop Or Observe Provisions Of A Pedestrian Crossing',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 83(3)',
    ),
    TrafficCode(
      code: 'D071',
      offenceDescription: 'Failing to use emergency warning sign',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 262(6)',
    ),
    TrafficCode(
      code: 'D072',
      offenceDescription: 'Failing To Yield Right Of Way at Pedestrian Crossing',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 83(3)',
    ),
    TrafficCode(
      code: 'D073',
      offenceDescription: 'Failing to yield right of way to emergency vehicles',
      fineAmount: 25000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 282(3)',
    ),
    TrafficCode(
      code: 'D074',
      offenceDescription: 'Fitting or using lamp fitted in contravention of the Regulations',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 85(9)',
    ),
    TrafficCode(
      code: 'D075',
      offenceDescription: 'Fraudulent Use Of Registration Plate or Decal',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(3)',
    ),
    TrafficCode(
      code: 'D076',
      offenceDescription: 'Leaving Motor Vehicle Unattended Without Stopping Engine',
      fineAmount: 3000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D077',
      offenceDescription: 'Leaving/Abandoning Motor Vehicle On Road Causing Obstruction',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 94(1)',
    ),
    TrafficCode(
      code: 'D078',
      offenceDescription: 'Licence Disc Not Affixed',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(5)',
    ),
    TrafficCode(
      code: 'D079',
      offenceDescription: 'More Person On Motor Cycle',
      fineAmount: 5000.0,
      demeritPoints: 3,
      legalSection: 'Section 67(2)',
    ),
    TrafficCode(
      code: 'D080',
      offenceDescription: 'No Brake Light',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(e)',
    ),
    TrafficCode(
      code: 'D081',
      offenceDescription: 'No Headlamp',
      fineAmount: 5000.0,
      demeritPoints: 4,
      legalSection: 'Section 71(2)(a)',
    ),
    TrafficCode(
      code: 'D082',
      offenceDescription: 'No Helmet',
      fineAmount: 8000.0,
      demeritPoints: 2,
      legalSection: 'Section 74(3)',
    ),
    TrafficCode(
      code: 'D083',
      offenceDescription: 'No Motor Vehicle Insurance',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Section 7(3)',
    ),
    TrafficCode(
      code: 'D084',
      offenceDescription: 'No Park Light',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(b)',
    ),
    TrafficCode(
      code: 'D085',
      offenceDescription: 'No Rear Registration Plate Light',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(d)',
    ),
    TrafficCode(
      code: 'D086',
      offenceDescription: 'No Reflectors',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(c)',
    ),
    TrafficCode(
      code: 'D087',
      offenceDescription: 'No Seat Belt In Motor Vehicle',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(g)',
    ),
    TrafficCode(
      code: 'D088',
      offenceDescription: 'No Valid Certificate Of Fitness',
      fineAmount: 15000.0,
      demeritPoints: 0,
      legalSection: 'Section 7(3)',
    ),
    TrafficCode(
      code: 'D089',
      offenceDescription: 'No Warning Devices',
      fineAmount: 5000.0,
      demeritPoints: 2,
      legalSection: 'Section 71(2)(f)',
    ),
    TrafficCode(
      code: 'D090',
      offenceDescription: 'Not Parked With Near Side Closed To The Left As Possible When Not In Motion',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D091',
      offenceDescription: 'Not producing transport emergency cards and manifests upon being requested to by a Constable or other authorized person',
      fineAmount: 175000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 291(3)',
    ),
    TrafficCode(
      code: 'D092',
      offenceDescription: 'Obscured Licence Disc',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(5)',
    ),
    TrafficCode(
      code: 'D093',
      offenceDescription: 'Obscured Registration Plate',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(5)',
    ),
    TrafficCode(
      code: 'D094',
      offenceDescription: 'Obstructing Traffic',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 93(3)',
    ),
    TrafficCode(
      code: 'D095',
      offenceDescription: 'Operating a driving school without being licensed',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 183(2)',
    ),
    TrafficCode(
      code: 'D096',
      offenceDescription: 'Operating a motor cycle on a road where any goods carried theron exceeds prescribed projection',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 257(3)',
    ),
    TrafficCode(
      code: 'D097',
      offenceDescription: 'Operating a motor vehicle that requires a special permit without obtaining such special permit',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 113(7)',
    ),
    TrafficCode(
      code: 'D098',
      offenceDescription: 'Operating Motor Vehicle Contrary To Terms and Conditions Of Licence',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(5)',
    ),
    TrafficCode(
      code: 'D099',
      offenceDescription: 'Operating Motor Vehicle Contrary To Terms Of Licence Issued To Dealer.',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(4)',
    ),
    TrafficCode(
      code: 'D100',
      offenceDescription: 'Operating motor vehicle contrary to the terms of Insurance coverage while acting as a driving instructor',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 180(2)',
    ),
    TrafficCode(
      code: 'D101',
      offenceDescription: 'Operating motor vehicle fitted with lamps emitting blue light or capable of emitting blue lights',
      fineAmount: 15000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 102(4)',
    ),
    TrafficCode(
      code: 'D102',
      offenceDescription: 'Operating motor vehicle fitted with spot lamp enabling beam of light to be deflected in any direction',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 101(3)',
    ),
    TrafficCode(
      code: 'D103',
      offenceDescription: 'Operating motor vehicle on a road where the overall height exceeds 4.2 metres from the ground',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 255(2)',
    ),
    TrafficCode(
      code: 'D104',
      offenceDescription: 'Operating motor vehicle or trailer where the load projects more than 15 centimetres beyond either side without the use of the required warning device to indicate the extent of the projection',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 258(6)',
    ),
    TrafficCode(
      code: 'D105',
      offenceDescription: 'Operating motor vehicle or trailer where the load projects more than 30 centimetres beyond the rear without the use of the required warning device to indicate the width or length of projection',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 258(6)',
    ),
    TrafficCode(
      code: 'D106',
      offenceDescription: 'Operating motor vehicle specified in Regulation 259(1) if the overall length of the vehicle exceeds that specified in Regulation 32',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 259(8)',
    ),
    TrafficCode(
      code: 'D107',
      offenceDescription: 'Operating motor vehicle specified in Regulation 259(1) if the overall width of the vehicle exceeds 3.5 meters',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 259(8)',
    ),
    TrafficCode(
      code: 'D108',
      offenceDescription: 'Operating motor vehicle specified in Regulation 259(1) if the overall width of the vehicle exceeds that specified in Regulation 33',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 259(8)',
    ),
    TrafficCode(
      code: 'D109',
      offenceDescription: 'Operating motor vehicle specified in Regulation 259(1) in time when motor vehicle cannot be clearly discerned at a distance of 150 meters',
      fineAmount: 500000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 259(8)',
    ),
    TrafficCode(
      code: 'D110',
      offenceDescription: 'Operating motor vehicle where exhaust pipe or silencer is not in good working order',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 66(2)',
    ),
    TrafficCode(
      code: 'D111',
      offenceDescription: 'Operating motor vehicle where exhaust pipe or silencer is placed and maintained so that exhaust or smoke leaks into the driving cab or passenger compartment',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 66(2)',
    ),
    TrafficCode(
      code: 'D112',
      offenceDescription: 'Operating motor vehicle where exhaust pipe or silencer when tested exceeds the Jamaica Motor Vehicle Exhaust Emission Standard limits',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 66(2)',
    ),
    TrafficCode(
      code: 'D113',
      offenceDescription: 'Operating motor vehicle where the exhaust or smoke from the engine causes nuisance or obstruction to the vision of other road users',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 66(2)',
    ),
    TrafficCode(
      code: 'D114',
      offenceDescription: 'Operating motor vehicle where the exhaust pipe or silencer is in such a position that oil or other flammable liquid or material can drip or fall onto the exhaust pipe or silencer',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 66(2)',
    ),
    TrafficCode(
      code: 'D115',
      offenceDescription: 'Operating Motor Vehicle Without Driver’s Licence/Permit',
      fineAmount: 40000.0,
      demeritPoints: 14,
      legalSection: 'Section 20(4)',
    ),
    TrafficCode(
      code: 'D116',
      offenceDescription: 'Overtaking Causing Obstruction',
      fineAmount: 10000.0,
      demeritPoints: 3,
      legalSection: 'Section 57(d)(ii)',
    ),
    TrafficCode(
      code: 'D117',
      offenceDescription: 'Parking In Such A Position As To Obstruct Traffic',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D118',
      offenceDescription: 'Passing Or Overtaking Vehicle Stopped At Pedestrian Crossing',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 83(3)',
    ),
    TrafficCode(
      code: 'D119',
      offenceDescription: 'Permitting another person to use motor vehicle not covered by insurance which includes coverage for driving instruction while acting as a driving instructor',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 180(2)',
    ),
    TrafficCode(
      code: 'D120',
      offenceDescription: 'Pouring Petrol With Engine Running Or With Naked Light',
      fineAmount: 4000.0,
      demeritPoints: 0,
      legalSection: 'Section 89(4)',
    ),
    TrafficCode(
      code: 'D121',
      offenceDescription: 'Providing services of a driving instructor without being certified by the Authority',
      fineAmount: 40000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 168(4)',
    ),
    TrafficCode(
      code: 'D122',
      offenceDescription: 'Refusal To Allow Vehicle To Be Weighed Or Tested',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Section 103(2)',
    ),
    TrafficCode(
      code: 'D123',
      offenceDescription: 'Riding on the outside of a vehicle',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 88(2)',
    ),
    TrafficCode(
      code: 'D124',
      offenceDescription: 'Selling, distributing or using a photographic image or video captured by an electronic enforcement device other than for the prosecution of a Part IV offence',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 242(4)',
    ),
    TrafficCode(
      code: 'D125',
      offenceDescription: 'Sitting or travelling or permitting person to sit or travel with load being transported',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 261(4)',
    ),
    TrafficCode(
      code: 'D126',
      offenceDescription: 'Smoking Ganja While Driving Or Attempting To Drive Or While Being In Charge Of A Vehicle On A Road',
      fineAmount: 10000.0,
      demeritPoints: 2,
      legalSection: 'Section 123',
    ),
    TrafficCode(
      code: 'D127',
      offenceDescription: 'Stopping or parking a non-emergency vehicle at a point within 3 metres of either side of  a fire hydrant without consent of a Constable or the Superintendent or other officer of the Jamaica Fire Brigade',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 284(2)',
    ),
    TrafficCode(
      code: 'D128',
      offenceDescription: 'Stopping within 12 metres of a bus stop sign',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 204(2)',
    ),
    TrafficCode(
      code: 'D129',
      offenceDescription: 'Towing motor vehicle on a toll road by means other than by a tow truck',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 249(5)',
    ),
    TrafficCode(
      code: 'D130',
      offenceDescription: 'Transporting dangerous goods while carrying passengers who are unqualified',
      fineAmount: 25000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 286(4)',
    ),
    TrafficCode(
      code: 'D131',
      offenceDescription: 'Transporting dangerous goods without being certified to do so',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 290(2)',
    ),
    TrafficCode(
      code: 'D132',
      offenceDescription: 'Travelling on or permitting a person to travel or drive in or on a motor vehicle or trailer while body protrudes beyond the side or rear',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 261(4)',
    ),
    TrafficCode(
      code: 'D133',
      offenceDescription: 'Unlawful Use Of Siren Or Other Similar Device',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 52(7)',
    ),
    TrafficCode(
      code: 'D134',
      offenceDescription: 'Unlicensed Motor Vehicle',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 7(3)',
    ),
    TrafficCode(
      code: 'D135',
      offenceDescription: 'Unregistered Motor Vehicle',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 7(3)',
    ),
    TrafficCode(
      code: 'D136',
      offenceDescription: 'Using a car to draw a trailer where the unladen weight equals or exceeds the weight of the drawing vehicle',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 250(2)',
    ),
    TrafficCode(
      code: 'D137',
      offenceDescription: 'Using a motor tractor to draw more than two trailers at one time',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 250(2)',
    ),
    TrafficCode(
      code: 'D138',
      offenceDescription: 'Using a revolving lamp in contravention of Regulation 103',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 103(7)',
    ),
    TrafficCode(
      code: 'D139',
      offenceDescription: 'Using a truck to draw more than one trailer at any one time',
      fineAmount: 30000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 250(2)',
    ),
    TrafficCode(
      code: 'D140',
      offenceDescription: 'Using an articulated motor vehicle to draw a trailer',
      fineAmount: 20000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 249(5)',
    ),
    TrafficCode(
      code: 'D141',
      offenceDescription: 'Using Electronic Communication Device While Driving Or Operating A Vehicle',
      fineAmount: 10000.0,
      demeritPoints: 4,
      legalSection: 'Section 121(4)',
    ),
    TrafficCode(
      code: 'D142',
      offenceDescription: 'Using motor vehicle on the road which is not licensed in accordance with the Act',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Section 13(5)',
    ),
    TrafficCode(
      code: 'D143',
      offenceDescription: 'Using motor vehicle to damage road sign',
      fineAmount: 50000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 203(3)',
    ),
    TrafficCode(
      code: 'D144',
      offenceDescription: 'Using motor vehicle to tow a broken down or disabled vehicle in contravention of Regulation 249(1)',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 249(5)',
    ),
    TrafficCode(
      code: 'D145',
      offenceDescription: 'Using motor vehicle while on a road that is not a main road to travel backwards longer than necessary for the safety or convenience of the occupants or other road users and traffic on the road',
      fineAmount: 5000.0,
      demeritPoints: 0,
      legalSection: 'Regulation 220(2)',
    ),
    TrafficCode(
      code: 'D146',
      offenceDescription: 'Using Wireless Communication Device To View Send Or Compose An Electronic Message While Driving',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 121(4)',
    ),
    TrafficCode(
      code: 'D147',
      offenceDescription: 'Wilfully Defacing Or Destroying Document',
      fineAmount: 10000.0,
      demeritPoints: 0,
      legalSection: 'Section 108(2)',
    ),
  ];
}
