import '../../models/westops/wanted_person.dart';

// TODO: Add `HttpWantedPersonsRepository` once the backend ships
// `/api/v1/westops/wanted-persons`. It should reuse the existing
// `HttpDocumentHubApiClient` in `lib/services/api/` rather than rolling its
// own transport.
abstract class WantedPersonsRepository {
  Future<List<WantedPerson>> listAll();
}

class InMemoryWantedPersonsRepository implements WantedPersonsRepository {
  const InMemoryWantedPersonsRepository();

  @override
  Future<List<WantedPerson>> listAll() async => _seedRecords;

  static final List<WantedPerson> _seedRecords = [
    WantedPerson(
      id: 'WP-1001',
      firstName: 'Damion',
      lastName: 'Brown',
      alias: 'Shotta',
      gender: 'Male',
      dateOfBirth: DateTime(1986, 3, 14),
      crimeDescription: 'Armed robbery — Three Mile, Kingston (Feb 2026).',
      photoUrl: 'https://ui-avatars.com/api/?name=Damion+Brown&size=256&background=random&color=fff&bold=true',
      rewardAmount: 250000,
      contactPhoneNumber: '876-555-0142',
      investigatingOfficer: 'D/Sgt. Kemar Lawrence #09745',
      investigatingOfficerSupervisor: 'D/Supt. Mark Russell #04528',
      stationContactNumber: '876-923-7152',
      stationName: "Hunt's Bay Police Station",
      stationNumber: 'STN-HB-027',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1002',
      firstName: 'Tashauna',
      lastName: 'Williams',
      alias: 'Tee',
      gender: 'Female',
      dateOfBirth: DateTime(1992, 9, 2),
      crimeDescription: 'Bank fraud — NCB Half-Way-Tree branch.',
      photoUrl: 'https://ui-avatars.com/api/?name=Tashauna+Williams&size=256&background=random&color=fff&bold=true',
      rewardAmount: 500000,
      contactPhoneNumber: '876-555-0177',
      investigatingOfficer: 'D/Cpl. Sherine Davis #13478',
      investigatingOfficerSupervisor: 'D/Insp. Roy Pinnock #08672',
      stationContactNumber: '876-926-8121',
      stationName: 'Half-Way-Tree Police Station',
      stationNumber: 'STN-HWT-001',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1003',
      firstName: 'Kemar',
      lastName: 'Henry',
      alias: 'Smiley',
      gender: 'Male',
      dateOfBirth: DateTime(1981, 11, 22),
      crimeDescription: 'Aggravated assault — Sam Sharpe Square, MoBay.',
      photoUrl: 'https://ui-avatars.com/api/?name=Kemar+Henry&size=256&background=random&color=fff&bold=true',
      rewardAmount: 150000,
      contactPhoneNumber: '876-555-0188',
      investigatingOfficer: 'D/Sgt. Tracy-Ann Brown #09921',
      investigatingOfficerSupervisor: 'D/Supt. Vernon Ellis #04201',
      stationContactNumber: '876-952-1557',
      stationName: 'Barnett Street Police Station',
      stationNumber: 'STN-BS-021',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1004',
      firstName: 'Andre',
      lastName: 'Campbell',
      alias: 'Capo',
      gender: 'Male',
      dateOfBirth: DateTime(1989, 6, 18),
      crimeDescription: 'Murder — Spanish Town, St Catherine.',
      photoUrl: 'https://ui-avatars.com/api/?name=Andre+Campbell&size=256&background=random&color=fff&bold=true',
      rewardAmount: 1000000,
      contactPhoneNumber: '119',
      investigatingOfficer: 'D/Insp. Wayne Morgan #07623',
      investigatingOfficerSupervisor: 'D/Supt. Lorna Christian #03812',
      stationContactNumber: '876-984-2305',
      stationName: 'Spanish Town Police Station',
      stationNumber: 'STN-ST-019',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1005',
      firstName: 'Marlon',
      lastName: 'Reid',
      gender: 'Male',
      dateOfBirth: DateTime(1994, 1, 5),
      crimeDescription: 'Larceny from dwelling — Mandeville, Manchester.',
      photoUrl: 'https://ui-avatars.com/api/?name=Marlon+Reid&size=256&background=random&color=fff&bold=true',
      rewardAmount: 75000,
      contactPhoneNumber: '876-555-0199',
      investigatingOfficer: 'D/Cpl. Sharon Walters #13251',
      investigatingOfficerSupervisor: 'D/Sgt. Howard Reid #08991',
      stationContactNumber: '876-962-2832',
      stationName: 'Mandeville Police Station',
      stationNumber: 'STN-MA-033',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1006',
      firstName: 'Jodian',
      lastName: 'Powell',
      alias: 'Jo',
      gender: 'Female',
      dateOfBirth: DateTime(1996, 4, 30),
      crimeDescription: 'Possession of illegal firearm — May Pen.',
      photoUrl: 'https://ui-avatars.com/api/?name=Jodian+Powell&size=256&background=random&color=fff&bold=true',
      rewardAmount: 200000,
      contactPhoneNumber: '876-555-0211',
      investigatingOfficer: 'D/Cpl. Andre Stewart #14087',
      investigatingOfficerSupervisor: 'D/Insp. Patrick Hines #08334',
      stationContactNumber: '876-986-2208',
      stationName: 'May Pen Police Station',
      stationNumber: 'STN-MP-029',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1007',
      firstName: 'Devon',
      lastName: 'Clarke',
      alias: 'Smoke',
      gender: 'Male',
      dateOfBirth: DateTime(1979, 8, 9),
      crimeDescription: 'Conspiracy to defraud — Ocho Rios tourism scheme.',
      photoUrl: 'https://ui-avatars.com/api/?name=Devon+Clarke&size=256&background=random&color=fff&bold=true',
      rewardAmount: 350000,
      contactPhoneNumber: '876-555-0223',
      investigatingOfficer: 'D/Sgt. Camille Roberts #09558',
      investigatingOfficerSupervisor: 'D/Insp. Garth Henry #07921',
      stationContactNumber: '876-974-2533',
      stationName: 'Ocho Rios Police Station',
      stationNumber: 'STN-OR-024',
      status: 'Wanted',
    ),
    WantedPerson(
      id: 'WP-1008',
      firstName: 'Shaneek',
      lastName: 'Morgan',
      gender: 'Female',
      dateOfBirth: DateTime(1990, 12, 14),
      crimeDescription: 'Wounding with intent — Savanna-la-Mar.',
      photoUrl: 'https://ui-avatars.com/api/?name=Shaneek+Morgan&size=256&background=random&color=fff&bold=true',
      rewardAmount: 100000,
      contactPhoneNumber: '876-555-0234',
      investigatingOfficer: 'D/Cpl. Nordia Brown #14689',
      investigatingOfficerSupervisor: 'D/Sgt. Trevor Campbell #08778',
      stationContactNumber: '876-955-2531',
      stationName: 'Savanna-la-Mar Police Station',
      stationNumber: 'STN-SV-040',
      status: 'Wanted',
    ),
  ];
}
